### ISSUE TITLE
MsIO in conda 

### ISSUE THREAD

**Issue by VinzentRisch** [rformassspectrometry/MsIO#22]
Hello 
I am currently working on creating a [Qiime2](https://github.com/qiime2/qiime2) package that uses XCMS for lc-ms data processing. 
I was searching for a good way to import and export the XCMSExperiment object to and from pain text. 
So I'm glad that this functionylity was implemented here.
I wanted to ask If there are any plans to make this package available through conda in the near future.
In Qiime2 I am limited to packages that are installable through conda.

**Comment by lgatto** [comment]
I think this is something to discuss with whoever manages R/Bioconductor package installation through `conda`. We don't handle this, as far as I know.

**Comment by VinzentRisch** [comment]
I dont quite understand what you mean with that. Are there specific people that make bioconductor packages available through conda?  
Are there plans to host MsIO on bioconductor?
Normally people add their packages to bioconda themselves through their [github](https://github.com/bioconda/bioconda-recipes).

**Comment by lgatto** [comment]
> Normally people add their packages to bioconda themselves through their [github](https://github.com/bioconda/bioconda-recipes).

As far as I know, we don't do it. 

And I suspect that somebody in the bioconda team automatically pulls R/Bioconductor github repos into bioconda every now and again.

**Comment by lgatto** [comment]
>  Are there plans to host MsIO on bioconductor?

Yes, MSnIO will eventually be submitted to Bioconductor, whenever it reaches a certain level of maturity. @jorainer might have an time estimate.

**Comment by jorainer** [comment]
We're planning to submit MsIO to Bioconductor - maybe already with the next release in Spring 2025. Also, let us know if there are specific things you would need for import/export of the data - or if some things don't work as expected.

**Comment by VinzentRisch** [comment]
Hi @jorainer 
That sounds great! But I can't wait that long. 
In the meantime I would like to try to create a conda recipe for the package and host it on a personal anaconda channel so that I can use it in my plugin until the package is properly released on bioconductor. 
For this to work the MsIO package would need a tag on the github page.
Would it be possible that you tag the current commit so i could use it?

**Comment by VinzentRisch** [comment]
So a release is not needed. 
Like this from the main branch:

`git tag -a v0.0.8 -m "Release version 0.0.8"`
`git push origin v0.0.8`

You can call it whatever you want of course i just saw the version in the DESCRIPTION.

Thank you so much!

**Comment by VinzentRisch** [comment]
Or sorry yes I meant create a release. The tags are also listed under releases in GitHub.
Sorry for the confusion.

**Comment by jorainer** [comment]
Done.

**Comment by VinzentRisch** [comment]
Thank you so much!

**Comment by VinzentRisch** [comment]
Hello @jorainer 
In November you said that you are planning to ass the MsIO package to bioconductor. Is this still the plan? When are you expecting to be able to release it on bioconductor?

**Comment by VinzentRisch** [comment]
Hey, thank you for the update!
